import fs from 'fs';
import path from 'path';
import os from 'os';

/**
 * Creates a temporary cookies file from the YT_COOKIES environment variable
 * to authenticate yt-dlp requests and bypass data center blocks.
 */
export function getCookiesPath(): string | null {
  const cookiesContent = process.env.YT_COOKIES;
  if (!cookiesContent) {
    console.log('[cookies] YT_COOKIES environment variable is not set or empty.');
    return null;
  }

  let trimmed = cookiesContent.trim();
  console.log('[cookies] YT_COOKIES length:', trimmed.length);

  // Check if base64 encoded
  if (!trimmed.startsWith('#') && !trimmed.startsWith('[') && !trimmed.startsWith('{') && /^[a-zA-Z0-9+/=]+$/.test(trimmed.replace(/\s/g, ''))) {
    console.log('[cookies] Detected potential Base64 encoding. Attempting to decode...');
    try {
      trimmed = Buffer.from(trimmed.replace(/\s/g, ''), 'base64').toString('utf-8').trim();
      console.log('[cookies] Decoded length:', trimmed.length);
    } catch (err) {
      console.error('[cookies] Failed to decode base64 cookies:', err);
    }
  }

  // Detect and convert JSON cookies to Netscape format
  if (trimmed.startsWith('[') || trimmed.startsWith('{')) {
    console.log('[cookies] Detected JSON format. Converting to Netscape format...');
    try {
      const jsonCookies = JSON.parse(trimmed);
      const cookieArray = Array.isArray(jsonCookies) ? jsonCookies : [jsonCookies];
      
      let netscapeContent = '# Netscape HTTP Cookie File\n# This file was generated by converting JSON cookies\n\n';
      
      for (const c of cookieArray) {
        if (!c.domain || !c.name) continue;
        
        const domain = c.domain;
        const subdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
        const path = c.path || '/';
        const secure = c.secure ? 'TRUE' : 'FALSE';
        const expiry = c.expirationDate ? Math.round(c.expirationDate).toString() : Math.round(Date.now() / 1000 + 86400 * 365).toString();
        const name = c.name;
        const value = c.value || '';
        
        netscapeContent += `${domain}\t${subdomains}\t${path}\t${secure}\t${expiry}\t${name}\t${value}\n`;
      }
      
      console.log('[cookies] Conversion complete. Netscape cookies lines:', netscapeContent.split('\n').length);
      trimmed = netscapeContent;
    } catch (err) {
      console.error('[cookies] Failed to parse JSON cookies:', err);
    }
  }

  const lines = trimmed.split('\n');
  console.log('[cookies] Total cookie lines:', lines.length);

  // Check for essential YouTube session cookie keys
  const essentialKeys = ['SID', 'HSID', 'SSID', 'APISID', 'SAPISID', '__Secure-1PSID', '__Secure-3PSID', 'LOGIN_INFO'];
  const presentKeys: string[] = [];
  lines.forEach(line => {
    if (!line.trim().startsWith('#') && line.trim() !== '') {
      const parts = line.split('\t');
      if (parts.length >= 6) {
        const cookieName = parts[parts.length - 2]?.trim();
        if (cookieName && essentialKeys.includes(cookieName) && !presentKeys.includes(cookieName)) {
          presentKeys.push(cookieName);
        }
      }
    }
  });
  console.log('[cookies] Detected YouTube Session Keys:', presentKeys.join(', ') || 'None');
  if (!presentKeys.includes('SID') && !presentKeys.includes('__Secure-3PSID')) {
    console.warn('[cookies] WARNING: SID and __Secure-3PSID cookies are missing! Full logged-in session cookies (SID, HSID, SSID, __Secure-3PSID, LOGIN_INFO) are required for YouTube authentication.');
  }

  try {
    const tempCookiesPath = path.join(os.tmpdir(), `yt_cookies_${Date.now()}.txt`);
    fs.writeFileSync(tempCookiesPath, trimmed, 'utf-8');
    return tempCookiesPath;
  } catch (err) {
    console.error('[cookies] Failed to write temporary cookies file:', err);
    return null;
  }
}

/**
 * Cleans up a temporary cookies file if it exists.
 */
export function cleanupCookiesFile(filePath: string | null) {
  if (!filePath) return;
  try {
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
    }
  } catch (err) {
    console.warn('[cookies] Failed to clean up temp cookies file:', err);
  }
}
